// <auto-generated />
using System;
using System.Text.Json;
using JobIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326160633_AddWebEnrichedAt")]
    partial class AddWebEnrichedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("JobsFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_fetched");

                    b.Property<int>("JobsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_new");

                    b.Property<int>("JobsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_removed");

                    b.Property<int>("JobsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_updated");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("running")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAt");

                    b.ToTable("collection_runs", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveJobCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_job_count");

                    b.Property<string>("AshbyBoardSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ashby_board_slug");

                    b.Property<double?>("AvgJobLifetimeDays")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_job_lifetime_days");

                    b.Property<double?>("AvgRepostCount")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_repost_count");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("canonical_name");

                    b.Property<DateTime?>("DescriptionEnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("description_enriched_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<int>("DuplicateJobCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duplicate_job_count");

                    b.Property<string>("EmployeeCountRange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_count_range");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("FoundingYear")
                        .HasColumnType("integer")
                        .HasColumnName("founding_year");

                    b.Property<string>("GreenhouseBoardToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("greenhouse_board_token");

                    b.Property<string>("HeadquartersCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("headquarters_city");

                    b.Property<string>("HeadquartersCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("headquarters_country");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<bool?>("IsTechHiring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tech_hiring");

                    b.Property<string>("LeverCompanySlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lever_company_slug");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("RemoteJobCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remote_job_count");

                    b.Property<int>("RemovedJobCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("removed_job_count");

                    b.Property<double?>("SalaryDisclosureRate")
                        .HasColumnType("double precision")
                        .HasColumnName("salary_disclosure_rate");

                    b.Property<string>("SmartRecruitersSlug")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StatsComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stats_computed_at");

                    b.Property<int>("TotalJobsEverSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_jobs_ever_seen");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("WebEnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WikidataEnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wikidata_enriched_at");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.Property<string>("WorkableSlug")
                        .HasColumnType("text");

                    b.Property<string>("WorkdayCareerSite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workday_career_site");

                    b.Property<string>("WorkdayHost")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workday_host");

                    b.HasKey("Id");

                    b.HasIndex("ActiveJobCount");

                    b.HasIndex("AshbyBoardSlug");

                    b.HasIndex("GreenhouseBoardToken");

                    b.HasIndex("LeverCompanySlug");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("WorkdayHost");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.CompanyJobSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveJobCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_job_count");

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("collection_run_id");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_count");

                    b.Property<int>("RemovedCount")
                        .HasColumnType("integer")
                        .HasColumnName("removed_count");

                    b.Property<DateTime>("SnapshotAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CollectionRunId");

                    b.HasIndex("CompanyId", "SnapshotAt");

                    b.ToTable("company_job_snapshots", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobPosting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplyUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("apply_url");

                    b.Property<string>("ApplyUrlDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apply_url_domain");

                    b.Property<string>("AuthenticityLabel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("authenticity_label");

                    b.Property<decimal?>("AuthenticityScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("authenticity_score");

                    b.Property<DateTime?>("AuthenticityScoreAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticity_scored_at");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("description_hash");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHybrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hybrid");

                    b.Property<bool>("IsRemote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_remote");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_city");

                    b.Property<string>("LocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_country");

                    b.Property<string>("LocationRaw")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_raw");

                    b.Property<string>("LocationState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_state");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<long?>("PreviousPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_posting_id");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<short>("RepostCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("repost_count");

                    b.Property<string>("SageMakerModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sagemaker_model_version");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("salary_currency");

                    b.Property<bool>("SalaryDisclosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("salary_disclosed");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("SalaryPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("salary_period");

                    b.Property<string>("SeniorityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seniority_level");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("PreviousPostingId");

                    b.HasIndex("AuthenticityLabel", "PostedAt");

                    b.HasIndex("CompanyId", "DescriptionHash");

                    b.HasIndex("CompanyId", "PostedAt");

                    b.HasIndex("IsActive", "PostedAt");

                    b.HasIndex("IsRemote", "PostedAt");

                    b.HasIndex("SeniorityLevel", "PostedAt");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExtractionMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extraction_method");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_posting_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("JobPostingId", "SkillId")
                        .IsUnique();

                    b.HasIndex("SkillId", "CreatedAt");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<JsonDocument>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_posting_id");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTime>("SnapshotAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "SnapshotAt");

                    b.ToTable("job_snapshots", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("api_version");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short?>("RateLimitRps")
                        .HasColumnType("smallint")
                        .HasColumnName("rate_limit_rps");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("job_sources", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.MlPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AuthenticityScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("authenticity_score");

                    b.Property<string>("EndpointName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint_name");

                    b.Property<JsonDocument>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("PredictedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("predicted_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "PredictedAt");

                    b.ToTable("ml_predictions", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.SkillTaxonomy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("ParentSkillId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_skill_id");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName")
                        .IsUnique();

                    b.HasIndex("ParentSkillId");

                    b.ToTable("skill_taxonomy", (string)null);
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.JobSource", "Source")
                        .WithMany("CollectionRuns")
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.CompanyJobSnapshot", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.CollectionRun", "CollectionRun")
                        .WithMany()
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobIntelligence.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionRun");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobPosting", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobIntelligence.Core.Entities.JobSource", "Source")
                        .WithMany("JobPostings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSkill", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.JobPosting", "JobPosting")
                        .WithMany("Skills")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobIntelligence.Core.Entities.SkillTaxonomy", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSnapshot", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.JobPosting", "JobPosting")
                        .WithMany("Snapshots")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.MlPrediction", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.JobPosting", "JobPosting")
                        .WithMany("MlPredictions")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.SkillTaxonomy", b =>
                {
                    b.HasOne("JobIntelligence.Core.Entities.SkillTaxonomy", "ParentSkill")
                        .WithMany("ChildSkills")
                        .HasForeignKey("ParentSkillId");

                    b.Navigation("ParentSkill");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.Company", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobPosting", b =>
                {
                    b.Navigation("MlPredictions");

                    b.Navigation("Skills");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.JobSource", b =>
                {
                    b.Navigation("CollectionRuns");

                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("JobIntelligence.Core.Entities.SkillTaxonomy", b =>
                {
                    b.Navigation("ChildSkills");

                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
